name: Build MangosSharp

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Solution_Path: ./src/server/Mangos.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET sdk
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore $Solution_Path

      - name: Build
        run: dotnet build --no-restore $Solution_Path

      - name: Test
        run: dotnet test --no-build --no-restore $Solution_Path

      - name: Verify
        run: dotnet format --verify-no-changes --no-restore $Solution_Path
